theme: jekyll-theme-hacker

title: CLIM 680 Final Project Report
description: Pliocene vs. Preindustrial Model Simulation Ouput Comparison
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chenpoju.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repository: planets # for github-metadata

permalink: pretty
