theme: jekyll-theme-cayman

title: CLIM 680 Final Project Report
description: Po Ju Chen
project: Miocene Simulations with Miocene aerosols v.s. Pre-industrial aerosols 

# Specify that things in the episodes collection should be output.
collections:
  earth:
    output: true
    permalink: /:path/index.html

# Set the default layout for things in the episodes collection.
defaults:
  - values:
      root: .
      layout: page
  - scope:
      path: ""
      type: earth
    values:
      root: ..
      layout: page
  
